import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author stefa
 */
public class CondominiumPanel extends JFrame {

    private User user;
    private JFrame parent;
    /**
     * Creates new form CondominiumPanel
     */
    public CondominiumPanel() {
        initComponents();
    }
    
    public CondominiumPanel(User user, JFrame parent) {
        initComponents();
                
        if(user == null) return;
        
        this.user = user;
        this.parent = parent;
        
        setTitle(user.getUserType() + " Access");
        if(user.getUserType().equals(UserType.SUPERADMIN)){
            this.btnAssociateManager.setEnabled(true);
                this.btnNewCondominium.setEnabled(true);
        }else if(user.getUserType().equals(UserType.MANAGER)){
             this.btnCondominium.setEnabled(true);
                this.btnApartments.setEnabled(true);
                this.btnChangePass.setEnabled(true);
                this.btnViewResidents.setEnabled(true);
                this.btnViewIdeas.setEnabled(true);
                this.btnAddResident.setEnabled(true);
        }else{
            this.btnViewProfile.setEnabled(true);
            this.btnIdeas.setEnabled(true);
            this.btnChangePass.setEnabled(true);
            this.btnViewIdeas.setEnabled(true);
        }
        
    }
    private void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssociateManager = new javax.swing.JButton();
        btnNewCondominium = new javax.swing.JButton();
        btnCondominium = new javax.swing.JButton();
        btnApartments = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnViewIdeas = new javax.swing.JButton();
        btnViewResidents = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        btnIdeas = new javax.swing.JButton();
        btnAddResident = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnAssociateManager.setText("Associate Manager");
        btnAssociateManager.setEnabled(false);
        btnAssociateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociateManagerActionPerformed(evt);
            }
        });

        btnNewCondominium.setText("New Condominium");
        btnNewCondominium.setEnabled(false);
        btnNewCondominium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCondominiumActionPerformed(evt);
            }
        });

        btnCondominium.setText("View Condominium");
        btnCondominium.setEnabled(false);
        btnCondominium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCondominiumActionPerformed(evt);
            }
        });

        btnApartments.setText("Apartments");
        btnApartments.setEnabled(false);
        btnApartments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartmentsActionPerformed(evt);
            }
        });

        btnChangePass.setText("Change Password");
        btnChangePass.setEnabled(false);
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnViewIdeas.setText("View Ideas");
        btnViewIdeas.setEnabled(false);
        btnViewIdeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIdeasActionPerformed(evt);
            }
        });

        btnViewResidents.setText("View Residents");
        btnViewResidents.setEnabled(false);
        btnViewResidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResidentsActionPerformed(evt);
            }
        });

        btnViewProfile.setText("View Profile");
        btnViewProfile.setEnabled(false);
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnIdeas.setText("Ideas");
        btnIdeas.setEnabled(false);
        btnIdeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdeasActionPerformed(evt);
            }
        });

        btnAddResident.setText("New Resident");
        btnAddResident.setEnabled(false);
        btnAddResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResidentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddResident, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewResidents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNewCondominium)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAssociateManager))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCondominium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewIdeas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApartments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIdeas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCondominium, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssociateManager, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCondominium, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApartments, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIdeas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewIdeas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddResident, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewResidents, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewCondominiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCondominiumActionPerformed
        SuperUserFrame condominiumManagement = new SuperUserFrame(this);        
        condominiumManagement.setVisible(true);
    }//GEN-LAST:event_btnNewCondominiumActionPerformed

    private void btnAssociateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociateManagerActionPerformed
        // TODO add your handling code here:
        AssociateManagerForm associateManagerForm = new AssociateManagerForm(this);        
        associateManagerForm.setVisible(true);
    }//GEN-LAST:event_btnAssociateManagerActionPerformed

    private void btnCondominiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCondominiumActionPerformed
        // TODO add your handling code here:
        CondominiumList form = new CondominiumList(user, this);
        form.setVisible(true);    
    }//GEN-LAST:event_btnCondominiumActionPerformed

    private void btnApartmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartmentsActionPerformed
        // TODO add your handling code here:
        ApartamentForm apartamentsForm = new ApartamentForm(user, this);
        apartamentsForm.setVisible(true);     
    }//GEN-LAST:event_btnApartmentsActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        ChangePassword cPassword = new ChangePassword(user, this);
        cPassword.setVisible(true);        
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnViewIdeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIdeasActionPerformed
        // TODO add your handling code here:
        IdeaForm form = new IdeaForm(user, this);
        form.setVisible(true);           
    }//GEN-LAST:event_btnViewIdeasActionPerformed

    private void btnViewResidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResidentsActionPerformed
        // TODO add your handling code here:
        SeeResidentsForm form = new SeeResidentsForm(user, this);
        form.setVisible(true);          
    }//GEN-LAST:event_btnViewResidentsActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ProfileView form = new ProfileView(user, this);
        form.setVisible(true);   
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnIdeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdeasActionPerformed
        IdeiasForm form = new IdeiasForm(user.getID(), this);
        form.setVisible(true);
    }//GEN-LAST:event_btnIdeasActionPerformed

    private void btnAddResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddResidentActionPerformed
        // TODO add your handling code here:
        residentregister form = new residentregister(user, this);
        form.setVisible(true);  
    }//GEN-LAST:event_btnAddResidentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CondominiumPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CondominiumPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CondominiumPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CondominiumPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CondominiumPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddResident;
    private javax.swing.JButton btnApartments;
    private javax.swing.JButton btnAssociateManager;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnCondominium;
    private javax.swing.JButton btnIdeas;
    private javax.swing.JButton btnNewCondominium;
    private javax.swing.JButton btnViewIdeas;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton btnViewResidents;
    // End of variables declaration//GEN-END:variables
}
